---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openeuler-website
spec:
  name: openeuler-website
  keysMap:
    api-user-pass:
      path: secrets/data/openeuler/website
      key: api_user_pass
    es-url:
      path: secrets/data/openeuler/website
      key: es_url
    es-user-pass:
      path: secrets/data/openeuler/website
      key: es_user_pass
    mail-user-pass:
      path: secrets/data/openeuler/website
      key: mail_user_pass
    mysql-database:
      path: secrets/data/openeuler/website
      key: mysql_database
    mysql-pwd:
      path: secrets/data/openeuler/website
      key: mysql_pwd
    mysql-url:
      path: secrets/data/openeuler/website
      key: mysql_url
    sig-api:
      path: secrets/data/openeuler/website
      key: sig_api
    client_id:
      path: secrets/data/infra-common/gitee-applications/openeuler-website
      key: client_id
    client_secret:
      path: secrets/data/infra-common/gitee-applications/openeuler-website
      key: client_secret
    cookie_secret:
      path: secrets/data/infra-common/gitee-applications/openeuler-website
      key: cookie_secret
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: purge-secrets
spec:
  name: purge-secrets
  keysMap:
    password:
      path: secrets/data/infra-common/nginx-purger
      key: password
    username:
      path: secrets/data/infra-common/nginx-purger
      key: username

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openeuler-org-tls
  namespace: website-v2
spec:
  name: openeuler-org-tls
  keysMap:
    ca.crt:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.crt
    tls.crt:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.crt
    tls.key:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.key
