# Config web frontend service
---
apiVersion: v1
kind: Service
metadata:
  name: website-frontend-service
spec:
  ports:
    - name: httpport
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    component: website-frontend
  type: ClusterIP

---
# Config web backend service
---
apiVersion: v1
kind: Service
metadata:
  name: website-backend-service
spec:
  ports:
    - name: httpport
      protocol: TCP
      port: 80
      targetPort: 8090
  selector:
    component: website-backend
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: cve-srv-service
spec:
  type: ExternalName
  externalName: cve-srv-service.cve.svc.cluster.local
---
kind: Service
apiVersion: v1
metadata:
  name: openeuler-meetingserver-internal
spec:
  type: ExternalName
  externalName: meeting-service.meetingserver.svc.cluster.local
---
kind: Service
apiVersion: v1
metadata:
  name: openeuler-api-cve
spec:
  type: ExternalName
  externalName: api-cve-service.api-cve.svc.cluster.local


