apiVersion: v1
items:
- apiVersion: v1
  data:
    default.conf: |
      server {
              listen 80;

              access_log  /var/log/nginx/host.access.log  main;
              server_name openeuler-repo.huawei.com;

              location / {
                  root   /repo/openeuler;
                  fancyindex on;
                  fancyindex_exact_size off;
                  fancyindex_header /fancySource/header.html;
                  fancyindex_footer /fancySource/footer.html;
                  autoindex   on;

              }
              location /fancySource {
                  root /etc/nginx/conf/static;
              }
              location = /favicon.ico {
                        log_not_found off;
                        access_log off;
              }
      }
    nginx.conf: |-
      user  root;
      worker_processes  6;

      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;


      events {
          worker_connections  10240;
      }


      http {
          include       /etc/nginx/conf/mime.types;
          default_type  application/octet-stream;
          server_tokens off;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;
          #tcp_nopush     on;

          keepalive_timeout  65;

          #gzip  on;

          include /etc/nginx/conf/conf.d/*.conf;
      }
    rsyncd.conf: |
      log file = /dev/stdout
      use chroot = yes
      uid = root
      gid = root
      max connections = 30
      timeout = 600
      read only = yes

      [openeuler]
              path = /repo/openeuler
              comment = openeuler repo folder
              read only = true
              #auth users = root
              #secrets file = /etc/rsyncd.secrets
              ignore nonreadable = yes
              refuse options = checksum
              dont compress = *
    ssh.pub: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChSk+/FF79F8ut0hpNuYQ4uhAgUSY4hzRIPvQ2uVTukP0B0A99NYPfDNICp7gLa6e7yzaj+bvCpgWZoZCNAWTBWkq+zHTgDDHrLtUE4zPC1guzuR+Gz3yeIzSt0iAzi9uG2p+qh7jUfl8QAwNOs3wosNenoZj7NmgsCF9M1o85msimRc8Roxnn5caao1RtdNkDHDqhw5QiS9doSUjoxT+esD0CI7RHAyMgMCfSlXXl/phpdSU2hVJSFXsHVBTiymkuMQe8Ylmls+OEmCe8Cy7lIqE/Q+56l62Pxv4UJpOWs9T/SrOEr5vtEPGghZzgo5ViewzAs3dGMaODSO25XhrIiRZ7hjBK9tjLOX7ZXfAsb4DpJljq2aPCrlEaGJsHc2laixKIOKogDbqFffM3eXwgEAxPUevX/mYnuyhAVrsRUl8HXIQnTuVIEeYVdmn2MA8I/y6MPWdN5VbLR5gOiNLOuSVhCq3sQLpTZ9CONF+zq+1layCoaGMIZw5JwYgWCQgCGNclbx8eMVY3+J3slH6VjzE/05Eys18HtpuAMCivBLGgpBGeCVdpQqkHodTn5ZjNZEBAgzHypiOgR/txMHhkTi4+1ZvTmSRWs9hggv4/IcDQFaj1f2JVds6lxGvJyOnoy9k1VUC0q4N6sptpJ/n+ElCJ4UaHE48La3Mu79R6+Q== openeuler_hosts
  kind: ConfigMap
  metadata:
    annotations:
    name: openeuler-configmap
    namespace: repo2
kind: List
