# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: repo-server
spec:
  strategy:
    # NOTE(tommylikehu): The strategy is recreate due to the multi-write issues if we running new pods while old one stays terminating.
    type: Recreate
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      nodeSelector:
        openeuler.ci/task: common
      containers:
        - name: repo-nginx
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/nginx-extras:1.21.0-with-fancy-templates-repo
          volumeMounts:
            - mountPath: /repo/openeuler
              name: data-volume-02
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          resources:
            requests:
              cpu: 2000m
              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /repo/openeuler_ex
              mkdir -p /repo/openeuler
              cp /root/.ssh/authorized_keys.ro /root/.ssh/authorized_keys
              chmod 0400 /root/.ssh/authorized_keys
              chown root:root /root/.ssh/authorized_keys
              ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
              ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
              ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
              /usr/sbin/sshd -D &
              exec nginx -g "daemon off;"
          securityContext:
            privileged: true
        - name: rsync-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/rsyncd:1.0.1
          volumeMounts:
            - mountPath: /etc/rsyncd.conf
              name: repo-nginx-configmap-volume
              subPath: rsyncd.conf
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
            - mountPath: /repo/openeuler
              name: data-volume-02          
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          resources:
            requests:
              cpu: 300m
              memory: 2000Mi
      volumes:
        - name: rsync-secrets-volume
          secret:
            secretName: rsync-secrets
        - name: data-volume-02
          persistentVolumeClaim:
            claimName: openeuler-data-volume-02
