---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: hdc-task-secrets
spec:
  name: hdc-task-secrets
  keysMap:
    db-passwd:
      path: secrets/data/openeuler/hdc-task-manager
      key: db-passwd
    db-uri:
      path: secrets/data/openeuler/hdc-task-manager
      key: db-uri
    db-username:
      path: secrets/data/openeuler/hdc-task-manager
      key: db-username
    aes-key:
      path: secrets/data/openeuler/hdc-task-manager
      key: aes-key
    hook-pwd:
      path: secrets/data/openeuler/hdc-task-manager
      key: hook-pwd
    gitee-token:
      path: secrets/data/openeuler/hdc-task-manager
      key: gitee-token
    cve-email-sendaddr:
      path: secrets/data/openeuler/hdc-task-manager
      key: cve-email-sendaddr
    cve-email-password:
      path: secrets/data/openeuler/hdc-task-manager
      key: cve-email-password
    gitee_gauss_token:
      path: secrets/data/openeuler/hdc-task-manager
      key: gitee-gauss-token
