---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-configmap
  namespace: repo-mirror
data:
  header.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <style type="text/css">
        body,html {
            background:#fff;
            font-family:"Bitstream Vera Sans","Lucida Grande",
            "Lucida Sans Unicode",Lucidux,Verdana,Lucida,sans-serif;
        }
        tr:nth-child(even) {
            background: rgba(0,0,0,.03);
        }
        th,td {
            padding:12px 0 12px 10px;
            word-wrap: break-word;
        }
        th {
            text-align: left;
            font-weight: bold;
            background: rgba(0,0,0,.05);
        }
        th a {
            color: #000;
        }
        #list {
            width: 1120px;
            margin: 0 auto;
        }
        a {
            color: #002fa7;
            text-decoration: none;
        }
        a:hover {
            color:#002fa7;
        }
        body>h1 {
            width: 1120px;
            margin: 20px auto;
        }
        @media screen and (max-width: 1120px){
            #list,body>h1 {width: 100%;}
            #list th{font-size: 14px;}
            #list td{font-size: 12px;}
            body>h1{font-size: 18px;}
        }
        </style>
        <link rel="stylesheet" href="/fancySource/css/index.css">
    </head>
    <body>
        <header>
            <div class="header">
                <div class="content">
                    <a href="https://openeuler.org/zh/">
                        <img src="/fancySource/img/openeuler.png" alt="" class="pc-logo" />
                        <img src="/fancySource/img/logo-mobile.png" alt="" class="mobile-logo" />
                    </a>
                </div>
            </div>
        </header>
        <div class="header-banner">
            <div class="content">
                <div class="text">
                    <h1>openEuler Repo</h1>
                    <p>We have mirror sites all over the world. Please visit our official
                        <a href="https://openeuler.org/zh/mirror/list/">mirror list</a> and select your desired one.</p>
                    <p>Here we provides the latest openEuler versions. In each version, you can find releases for a variety
                    of scenarios, including server, cloud native, edge computing, and embedded.</p>
                    <p>To download historical openEuler versions, click
                        <a href="https://archives.openeuler.openatom.cn/">here</a>.</p>
                    <p>If you have any question, please <a href="mailto:infra@openeuler.sh">contact us</a>.</p>
                </div>
                <div class="image">
                    <h1>openEuler Repo</h1>
                    <img src="/fancySource/img/repo-banner.png" alt="" />
                </div>
            </div>
        </div>
    </body>
    </html>
    <h1>Index of
